### ISSUE TITLE
Compatibility with Mathematica 13.0

### ISSUE THREAD

**Issue by davi-rodrigues** [mark-caprio/CustomTicks#3]
I am having an issue with CustomTicks within Mathematica 13.0. The issue is detailed [here in StackExchange](https://mathematica.stackexchange.com/questions/261270/customticks-and-mathematica-13-0)

It seems that LinTicks is not working, but LogTicks works (at least in part).

**Comment by mark-caprio** [comment]
Fixed by 4be303e.
